### PR TITLE
Added Contact Thumbnail feature

### PR DESCRIPTION
**Pull request by peterchibunna**
Contact photo as thumbnail will be accessible via the `thumbnail` property.

### CODE REVIEW

**Comment by dbaq** [comment]
hello @peterchibunna, thank you so much for contributing. 

I have 2 questions/comments:
- can you please update the examples in the readme file please?
- have you looked for iOS to see if it is possible to mirror the changes?

thanks

**Comment by peterchibunna** [comment]
I don't have an iOS phone at the moment but I will get one soon and then attempt to mirror the changes. Regarding the READMe example update, I will do that.

**Comment by dbaq** [comment]
@peterchibunna, can you please address the 2 points mentioned above?

**Comment by kodeine** [comment]
Any word on this?

**Comment by peterchibunna** [comment]
Yes, I just updated the README file. I wasn't able to do this for iOS. I don't have an iPhone please.

**Comment by dbaq** [comment]
@peterchibunna I don't see your changes on the README file, did you forget to push?

I'll merge this right after.

**Comment by peterchibunna** [comment]
Sorry, I just did.

**Comment by dbaq** [comment]
@peterchibunna, thank you for your contribution 👍

**Pull request merged**
