### PR TITLE
Added support for android 23

### PR DESCRIPTION
**Pull request by uriva**

### CODE REVIEW

**Comment by dbaq** [comment]
hey @uriva, 

Thanks for the contribution. I do not understand the commit 8f5a349. Which bug? Why all these changes? Can you please clean the PR to avoid changes due to formatting.

Thanks

**Comment by uriva** [comment]
Yeah that was done by mistake (autoformatter) and would be difficult to revert. If you give me an automatic way to format it the way you like I will.

Also a diff tool that ignores whitespace might be helpful to see the real changes.

**Comment by uriva** [comment]
This is what I use: http://astyle.sourceforge.net/

**Comment by dbaq** [comment]
I am sorry @uriva, I can't accept this PR with all these changes. The history of that file would be ruined. You can easily rebase your branch to remove your last commit and apply in another commit the changes without changing the formatting of the file.

**Comment by uriva** [comment]
I did as you wished

**Comment by dbaq** [comment]
Thanks @uriva, I appreciate it. :+1:

**Pull request merged**
